name: Publish

on:
  push:
    branches: [ "master" ]
  workflow_call:
    secrets:
      SIGN_KEY_ALIAS:
        required: true
      SIGN_KEY_PASSWORD:
        required: true
      SIGN_KEYSTORE_PASSWORD:
        required: true
      SIGN_KEYSTORE_DATA:
        required: true

permissions:
  contents: read

jobs:
  build:
    uses: MinecraftForge/SharedActions/.github/workflows/gradle.yml@main
    with:
      java: 8
      gradle_tasks: "publish"
      artifact_name: "installertools"
      gradle_setup: |-
        export SIGN_KEY_ALIAS=${{ secrets.SIGN_KEY_ALIAS }}
        export SIGN_KEY_PASSWORD=${{ secrets.SIGN_KEY_PASSWORD }}
        export SIGN_KEYSTORE_PASSWORD=${{ secrets.SIGN_KEYSTORE_PASSWORD }}
        export SIGN_KEYSTORE_DATA=${{ secrets.SIGN_KEYSTORE_DATA }}
