name: Publish

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    uses: MinecraftForge/SharedActions/.github/workflows/gradle.yml@main
    with:
      java: 8
      gradle_tasks: "publish"
      artifact_name: "installertools"
      gradle_setup: |-
        export SIGN_KEY_ALIAS=${{ secrets.SIGN_KEY_ALIAS }}
        export SIGN_KEY_PASSWORD=${{ secrets.SIGN_KEY_PASSWORD }}
        export SIGN_KEYSTORE_PASSWORD=${{ secrets.SIGN_KEYSTORE_PASSWORD }}
        export SIGN_KEYSTORE_DATA=${{ secrets.SIGN_KEYSTORE_DATA }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      PROMOTE_ARTIFACT_WEBHOOK: ${{ secrets.PROMOTE_ARTIFACT_WEBHOOK }}
      PROMOTE_ARTIFACT_USERNAME: ${{ secrets.PROMOTE_ARTIFACT_USERNAME }}
      PROMOTE_ARTIFACT_PASSWORD: ${{ secrets.PROMOTE_ARTIFACT_PASSWORD }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
